production:
    adapter: postgresql
    database: Weddingz_production
    username: postgres
    password: password
    host: localhost
    encoding: UTF8

test:
    adapter: postgresql
    database: Weddingz_test
    username: postgres
    password: password
    host: localhost
    encoding: UTF8
    
development:
    adapter: postgresql
    database: Weddingz_development
    username: postgres
    password: password
    host: localhost
    encoding: UTF8