production:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: Weddingz_production
    pool: 5
    username: root
    password:
    socket: /tmp/mysql.sock

test:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: Weddingz_test
    pool: 5
    username: root
    password:
    socket: /tmp/mysql.sock
    
development:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: Weddingz_development
    pool: 5
    username: root
    password:
    socket: /tmp/mysql.sock